### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN:

{
  "description": "찹쌀떡 시리즈",
  "items": [
    {
      "name": "단팥-플레인",
      "price": 5000,
      "count": 5
    }
  ],
  "name": "나이키 찹살떡4"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN:

{
  "productId": 1,
  "count": 5,
  "name": "단호박-딸기",
  "price": 10000
}

### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN:

{
  "id": 1,
  "description": "상품 수정",
  "name": "나이키 에어포스 수정",
  "items": [
    {
      "id": 1,
      "name": "270",
      "price": 100000,
      "count": 5
    }
  ]
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN:

{
  "id": 1,
  "count": 100,
  "name": "270",
  "price": 10000
}

### 상품 삭제
DELETE http://localhost:8082/seller/product?id=1
X-AUTH-TOKEN:

### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=1
X-AUTH-TOKEN:

### 상품 검색
GET http://localhost:8082/search/product?name=나이키
Content-Type: application/json

### 상품 디테일 검색
GET http://localhost:8082/search/product/detail?id=1
Content-Type: application/json

### 카트 추가
POST http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN:

{
  "description": "찹쌀떡 시리즈",
  "id": 1,
  "items": [
    {
      "count": 1,
      "id": 1,
      "name": "단호박-플레인",
      "price": 5000
    }
  ],
  "name": "나이키 찹쌀떡1",
  "sellerId": 1
}

### 카트 조회
GET http://localhost:8082/customer/cart
X-AUTH-TOKEN:

### 카트 업데이트
PUT http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN:

{
  "customerId": 1,
  "messages": [],
  "products": [
    {
      "description": "찹쌀떡 시리즈",
      "id": 1,
      "items": [
        {
          "count": 2,
          "id": 1,
          "name": "단호박-플레인",
          "price": 5000
        }
      ],
      "name": "나이키 찹쌀떡0",
      "sellerId": 1
    }
  ]
}

### 카트 주문
POST http://localhost:8082/customer/cart/order
Content-Type: application/json
X-AUTH-TOKEN:

{
  "customerId": 1,
  "messages": [],
  "products": [
    {
      "description": "찹쌀떡 시리즈",
      "id": 1,
      "items": [
        {
          "count": 1,
          "id": 1,
          "name": "단호박-플레인",
          "price": 5000
        }
      ],
      "name": "나이키 찹쌀떡1",
      "sellerId": 1
    }
  ]
}